# ------------------
# Ejemplo base de Sidecar: Es probable que cuando lo desploiegue en Kubernetes deba modificar este archivo
# ------------------
metadata:
  name: propertiesalpes
  labels:
    app: backend
spec:
  containers:
    - name: propertiesalpes
      image: # Imagen en Image Registry
    - name: adaptador-grpc
      image: # Imagen en Image Registry

---

# Service Configuration
# --------------------
apiVersion: v1
kind: Service
metadata:
  name: propertiesalpes-backend
spec:
  ports:
  - port: 50051
    protocol: TCP
  selector:
    app: backend
  type: NodePort